from collections.abc import Mapping, Sequence

type QueryParameter = str | int | None
type QueryParameters = Sequence[QueryParameter] | Mapping[str, QueryParameter]

class PostgresDatabaseError(RuntimeError):
    sqlstate: str
    severity: str
    message_primary: str
    detail: str | None
    hint: str | None
    schema_name: str | None
    table_name: str | None
    column_name: str | None
    datatype_name: str | None
    constraint_name: str | None

class PostgresIntegrityError(PostgresDatabaseError): ...
class PostgresDataError(RuntimeError): ...
class PostgresInterfaceError(RuntimeError): ...
class PostgresNotSupportedError(RuntimeError): ...
class PostgresOperationalError(RuntimeError): ...
class PostgresProgrammingError(RuntimeError): ...
class PoolHandle: ...
class TransactionHandle: ...

def build_info() -> tuple[str, str]: ...
def create_pool(
    database_url: str,
    max_size: int = 16,
    wait_timeout_ms: int = 30_000,
) -> PoolHandle: ...
async def runtime_probe(delay_ms: int) -> int: ...
async def close_pools() -> None: ...
async def close_pool(pool: PoolHandle) -> None: ...
async def begin_transaction(
    pool: PoolHandle,
    isolation_level: str | None = None,
    read_only: bool | None = None,
    deferrable: bool | None = None,
) -> TransactionHandle: ...
async def execute_transaction(
    transaction: TransactionHandle,
    sql: str,
    params: QueryParameters | None = None,
) -> list[list[str | int | None]]: ...
async def execute_transaction_result(
    transaction: TransactionHandle,
    sql: str,
    params: QueryParameters | None = None,
) -> tuple[list[list[str | int | None]], int]: ...
async def execute_transaction_with_metadata(
    transaction: TransactionHandle,
    sql: str,
    params: QueryParameters | None = None,
) -> tuple[list[list[str | int | None]], int, list[str]]: ...
async def commit_transaction(transaction: TransactionHandle) -> None: ...
async def rollback_transaction(transaction: TransactionHandle) -> None: ...
async def execute(
    pool: PoolHandle,
    sql: str,
    params: QueryParameters | None = None,
) -> list[list[str | int | None]]: ...
async def execute_result(
    pool: PoolHandle,
    sql: str,
    params: QueryParameters | None = None,
) -> tuple[list[list[str | int | None]], int]: ...
async def execute_with_metadata(
    pool: PoolHandle,
    sql: str,
    params: QueryParameters | None = None,
) -> tuple[list[list[str | int | None]], int, list[str]]: ...
