from collections.abc import Sequence

class PoolHandle: ...
class TransactionHandle: ...

def build_info() -> tuple[str, str]: ...
def create_pool(
    database_url: str,
    max_size: int = 16,
    wait_timeout_ms: int = 30_000,
) -> PoolHandle: ...
async def runtime_probe(delay_ms: int) -> int: ...
async def close_pools() -> None: ...
async def close_pool(pool: PoolHandle) -> None: ...
async def begin_transaction(pool: PoolHandle) -> TransactionHandle: ...
async def execute_transaction(
    transaction: TransactionHandle,
    sql: str,
    params: Sequence[str | int] | None = None,
) -> list[list[str | int | None]]: ...
async def commit_transaction(transaction: TransactionHandle) -> None: ...
async def rollback_transaction(transaction: TransactionHandle) -> None: ...
async def execute(
    pool: PoolHandle,
    sql: str,
    params: Sequence[str | int] | None = None,
) -> list[list[str | int | None]]: ...
