[build-system]
requires = ["maturin>=1.9,<2.0"]
build-backend = "maturin"

[project]
name = "django-native-postgres"
dynamic = ["version"]
description = "Native asynchronous PostgreSQL execution for Django"
readme = "README.md"
requires-python = ">=3.12"
license = "BSD-3-Clause"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Framework :: Django",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
    "Programming Language :: Rust",
    "Topic :: Database",
]
dependencies = [
    "Django==6.2.dev20261009125329",
    "psycopg>=3.1.12",
]

[project.urls]
Changelog = "https://github.com/p-r-a-v-i-n/django-native-postgres/blob/main/CHANGELOG.md"
Documentation = "https://github.com/p-r-a-v-i-n/django-native-postgres/tree/main/docs"
Issues = "https://github.com/p-r-a-v-i-n/django-native-postgres/issues"
Repository = "https://github.com/p-r-a-v-i-n/django-native-postgres"

[dependency-groups]
dev = [
    "maturin>=1.9,<2.0",
    "psycopg[binary]>=3.1.12",
    "pytest>=8",
    "pytest-asyncio>=1.4.0",
    "pytest-django>=4.14.0",
    "ruff>=0.12",
]

[tool.maturin]
bindings = "pyo3"
python-source = "python"
module-name = "django_native_postgres._native"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I", "UP"]

[tool.uv.sources]
django = { git = "https://github.com/p-r-a-v-i-n/django.git", rev = "312860d0e58e0d54fef10bae7ecf63f537723d17" }
