import django.db.models.deletion
from django.db import migrations, models

import tests.integration_app.models


class Migration(migrations.Migration):
    dependencies = [
        ("integration_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeletionParent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="CascadeChild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="integration_app.deletionparent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CallableSetChild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET(tests.integration_app.models.set_null),
                        to="integration_app.deletionparent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CascadeGrandchild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="integration_app.cascadechild",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NullableChild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="integration_app.deletionparent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProtectedChild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="integration_app.deletionparent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProtectedGrandchild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="integration_app.cascadechild",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RestrictedChild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="integration_app.deletionparent",
                    ),
                ),
            ],
        ),
    ]
